name: Push Container

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15

      - name: Build Image
        run: docker load --input $(nix build .#image --print-out-paths)

      - name: Push Image
        run: |
          export NIXTAG="$(docker image ls ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tail -n1 | awk -F' ' '{print $2}')"
          echo $NIXTAG
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${NIXTAG} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}